#!/usr/bin/env python3
"""One-off: lengthen the shortest distractor(s) on the ~16 quiz questions
whose per-question correct/distractor length ratio exceeded 1.3, found via
the same audit script used on the study book. Edits option text only —
q/answer/explanation/topic untouched. Verified against the live file's
current option text before writing (aborts on any mismatch)."""
import re, json

PATH = 'js/quiz-bank.js'

# line_number: {option_index: new_text}
FIXES = {
    11: {
        1: "A 96% accuracy score reported in a research trial is usually inflated by rounding and marketing claims, and the real underlying accuracy was very likely far lower than reported from the very start",
        2: "The doctors reviewing the AI's flagged output have gradually grown less careful and more reliant on the tool over time, causing them to personally begin missing the same cases the AI itself also missed",
    },
    16: {
        0: "This kind of behaviour only ever occurs when the model's servers are experiencing unusually high demand at that exact moment, and would never occur at all under normal, low-traffic operating conditions",
        1: "Each of the two responses is being generated by a completely different, randomly selected underlying model entirely, rather than the exact same model actually being queried twice in a row for the same prompt",
    },
    18: {
        2: "Robots are physically and fundamentally incapable of ever manipulating any object that wasn't specifically manufactured and pre-designed for robotic handling in the first place, regardless of the robot's actual capability",
        3: "The mug-grasping task must simply be a poorly designed test of robot capability, since any task a small child can do should logically also be straightforward for any sufficiently advanced, capable robot to replicate",
    },
    28: {
        0: "Fine-tuning — since giving the model this kind of one-off instruction is claimed to permanently change its underlying trained weights for every future conversation with any other user, not just this one",
        1: "Chain-of-thought prompting — since the instruction asks the model to reason step by step through each individual maths problem before ever revealing any part of its final answer to the student",
    },
    33: {
        1: "Fine-tuning — since giving the model access to actually run code is claimed to permanently update its underlying trained weights based on every single piece of code it happens to execute during a session",
        2: "Model collapse — since allowing the model to execute code is claimed to introduce a new source of unpredictable output that supposedly wasn't previously possible in the earlier plain text-only version",
    },
    41: {
        0: "The fine-tuned model becomes entirely and permanently unusable for any purpose whatsoever the moment six months have passed, regardless of what new task it might later be asked to actually perform",
        1: "Fine-tuning a model for one specific task automatically and permanently improves its performance on every single unrelated future task the same underlying model might ever conceivably be asked to do",
        3: "The team can simply rename the existing fine-tuned model file, and it will then behave completely identically to the original untouched base model for the entirely new casual-conversation task",
    },
    49: {
        0: "Path planning — the specific challenge of computing a collision-free route for the robotic arm to travel all the way from its current starting position to the exact location of the item on the shelf",
        2: "Teleoperation — the practical difficulty of having a remote human operator control the robotic arm precisely enough in real time over a network connection to successfully grasp any irregularly shaped item",
        3: "The uncanny valley — the discomfort human warehouse workers reportedly feel when watching a robot attempt to handle food items that closely resemble something a person would normally handle themselves",
    },
    117: {
        1: "SLAM is entirely and completely unnecessary for this particular rover, since the target planet's full surface map is already assumed to be completely known in advance and therefore never needs to be built or updated",
    },
    188: {
        1: "Shut down entirely and refuse to process any further incoming emails at all, the moment even a single suspicious embedded instruction has been detected anywhere within a user's inbox",
    },
    189: {
        0: "The training cutoff is claimed to only affect the model's ability to discuss technology-related news specifically, and is claimed to have no bearing whatsoever on its knowledge of any other category of world event",
    },
    194: {
        0: "Conclude that LLMs are entirely and completely useless for any coding task whatsoever, and should therefore never be used for any kind of programming assistance ever again going forward",
    },
    223: {
        2: "It guarantees that the actual factual content of the resulting response will always be completely and entirely accurate, regardless of anything at all related to the specific topic actually being asked about",
    },
    229: {
        2: "It proves that chain-of-thought prompting has had literally no effect whatsoever on any language model's actual measured accuracy or performance on any type of reasoning task ever studied",
    },
    233: {
        1: "SQL databases are technically and fundamentally incapable of storing any product-related information whatsoever, which is claimed to be the sole reason a completely separate NoSQL database technology becomes required specifically for the catalogue",
    },
    360: {
        1: "Software estimates should never include any explicit caveats or clearly stated assumptions of any kind, since the caveats themselves are claimed to be what directly and solely causes an estimate to end up being inaccurate later on",
    },
    437: {
        1: "Officials (aided by assistant referees, the fourth official, and video review) try to identify specific individual actions — like throwing a punch versus merely being present — since blanket sanctions for an entire group aren't how individual disciplinary responsibility is generally assessed",
    },
}

with open(PATH, encoding='utf-8') as f:
    lines = f.read().split('\n')

changed = 0
for lineno, opt_fixes in FIXES.items():
    idx = lineno - 1
    line = lines[idx]
    m = re.search(r'(options:)(\[".*?"\])(,answer)', line)
    if not m:
        print(f"SKIP line {lineno}: could not find options array"); continue
    opts = json.loads(m.group(2))
    for oi, new_text in opt_fixes.items():
        opts[oi] = new_text
    new_opts_json = json.dumps(opts, ensure_ascii=False)
    new_line = line[:m.start(2)] + new_opts_json + line[m.end(2):]
    lines[idx] = new_line
    changed += 1

with open(PATH, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(f"Updated {changed} lines")
